initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate 
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate
            + initialAmount * rate;
            initialAmount * 0.25 + initialAmount;
